git: pre-commit: check format with clang-format
Signed-off-by: Rong Tao <rongtao@cestc.cn>
Envs: CPU Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz, Arch x86_64
Vers: Fedora Linux 43, Linux 6.17.12-300.fc43.x86_64, GCC 15.2.1, glibc 2.42, GIT 2.52.0

diff --git a/scripts/git/hooks/pre-commit b/scripts/git/hooks/pre-commit
--- a/scripts/git/hooks/pre-commit
+++ b/scripts/git/hooks/pre-commit
@@ -14,14 +14,26 @@ if [[ ${V} ]] || [[ ${VERBOSE} ]]; then
 	set -x
 fi
 
+fatal() {
+	echo >&2 -en "\033[31m"
+	echo >&2 -e "FATAL: "${@}
+	echo >&2 -en "\033[0m"
+	exit 1
+}
+
+# Check code format wich git-clang-format
+clang_format=$(which git-clang-format 2>/dev/null || :)
+if  [[ -z ${clang_format} ]] && [[ -z ${FORCE} ]]; then
+	fatal "Not found git-clang-format, please install or FORCE=1"
+elif [[ -z ${FORCE} ]]; then
+	${clang_format} --diff origin/main --extensions c,cpp,h,hpp || {
+		fatal "Bad code format, please modify according to the above diff or FORCE=1"
+	}
+fi
+
 try_add=( $(git status --short | grep ^A | awk '{print $2}' || true) )
 try_del=( $(git status --short | grep ^D | awk '{print $2}' || true) )
 try_modify=( $(git status --short | grep ^M | awk '{print $2}' || true) )
-
-fatal() {
-	echo >&2 "FATAL: "${@}
-	exit 1
-}
 
 # Redirect output to stderr.
 exec 1>&2
@@ -31,14 +43,14 @@ hint_changelog() {
 	  ! [[ -L ${GIT_TOPDIR}/CHANGELOG.md ]]; then
 		if ! [[ " ${try_modify[@]} " =~ " CHANGELOG.md " ]]; then
 			git status --short
-			fatal "${@}" "you forgot modify CHANGELOG!!! Try FORCE???"
+			fatal "${@}" "you forgot modify CHANGELOG!!! Try FORCE=1???"
 		fi
 	fi
 	if [[ -f ${GIT_TOPDIR}/docs/en/CHANGELOG.md ]]; then
 		if [[ ! " ${try_modify[@]} " =~ " docs/en/CHANGELOG.md " ]] ||
 		   [[ ! " ${try_modify[@]} " =~ " docs/zh/CHANGELOG.md " ]]; then
 			git status --short
-			fatal "${@}" "you forgot modify docs/{en,zh}/CHANGELOG.md!!! Try FORCE???"
+			fatal "${@}" "you forgot modify docs/{en,zh}/CHANGELOG.md!!! Try FORCE=1???"
 		fi
 	fi
 }
