git: hooks/prepare-commit-msg: add FORCE=1
Signed-off-by: Rong Tao <rtoax@foxmail.com>
Envs: CPU Cortex-X925 Cortex-A725, Arch aarch64
Vers: Ubuntu 24.04, Linux 6.14.0-1015-nvidia, GIT 2.43.0

diff --git a/scripts/git/hooks/prepare-commit-msg b/scripts/git/hooks/prepare-commit-msg
--- a/scripts/git/hooks/prepare-commit-msg
+++ b/scripts/git/hooks/prepare-commit-msg
@@ -1,5 +1,8 @@
 #!/bin/bash
 # Copyright (C) 2025 Rong Tao
+#
+# Env: [FORCE=1] git commit ...
+#
 
 readonly COMMIT_MSG_FILE=$1
 readonly COMMIT_SOURCE=$2 # commit, merge
@@ -30,7 +33,7 @@ Environments=""
 
 fatal() {
 	echo >&2 "FATAL: "${@}
-	exit 1
+	[[ -z ${FORCE} ]] && exit 1
 }
 
 warning() {
@@ -39,7 +42,11 @@ warning() {
 
 add_ver() {
 	[[ -z "${@}" ]] && fatal "Bad call of add_ver()"
-	[[ -z "$(echo ${@} | grep -oE '[0-9]')" ]] && fatal "Can't found version in '${@}'"
+	if [[ -z "$(echo ${@} | grep -oE '[0-9]')" ]]; then
+		fatal "Can't found version in '${@}'"
+		# Return directly if FORCE
+		return 0
+	fi
 
 	# Already exist
 	if [[ "${Versions}" =~ "${@}" ]]; then
