Doc: ruankao: update
Vers: Ubuntu 25.10, Linux 6.17.0-19-generic, Bash 5.2.37, LaTeXmk 4.87, Sphinx 8.2.3, Git 2.51.0, Python 3.13.7
Signed-off-by: Rong Tao <rongtao@cestc.cn>

diff --git a/scripts/git/hooks/prepare-commit-msg b/scripts/git/hooks/prepare-commit-msg
--- a/scripts/git/hooks/prepare-commit-msg
+++ b/scripts/git/hooks/prepare-commit-msg
@@ -470,6 +470,17 @@ if [[ "$(has_key ai pytorch python py)" ]]; then
 	py_ver
 fi
 
+# If only modify The Documentation, try add Commit Message Title
+if [[ -z "$(git status --short | grep -v -e Documentation -e prepare-commit-msg || :)" ]]; then
+	doc_files=( $(git status --short | grep -Eo 'Documentation.*' | grep -vw conf.py) )
+	doc_dirs=( $(basename $(dirname ${doc_files[@]}) ) )
+	doc_label=$(IFS=,; echo "${doc_dirs[*]}")
+	sed -i "1i Doc: ${doc_label}: update " ${COMMIT_MSG_FILE} || {
+		fatal "Failed add commit message"
+	}
+
+fi
+
 # Add lines
 if [[ ${Versions} ]]; then
 	sed -i "$((${signed_off_by_line}+1))i Vers: ${Versions}" ${COMMIT_MSG_FILE} || {
